export const seedUsers = [
  { id: 'admin', name: 'Super Admin', role: 'Super Admin', department: 'Operations', password: 'Zuari@54321' },
  { id: 'subadmin', name: 'Admin User', role: 'Admin', department: 'Admin', password: 'ADMIN@12345' },
  { id: 'hr', name: 'HR User', role: 'Employee', department: 'HR', password: 'HR@12345' },
  { id: 'finance', name: 'Finance User', role: 'Employee', department: 'Finance', password: 'FINANCE@12345' },
  { id: 'it', name: 'IT User', role: 'Employee', department: 'IT', password: 'IT@12345' },
  { id: 'backoffice', name: 'Back Office User', role: 'Employee', department: 'Back Office', password: 'BACKOFFICE@12345' },
  { id: 'rms', name: 'RMS User', role: 'Employee', department: 'RMS', password: 'RMS@12345' },
  { id: 'mfo', name: 'MFO User', role: 'Employee', department: 'MFO', password: 'MFO@12345' },
  { id: 'rta', name: 'RTA User', role: 'Employee', department: 'RTA', password: 'RTA@12345' },
  { id: 'cs', name: 'CS User', role: 'Employee', department: 'CS', password: 'CS@12345' },
  { id: 'compliance', name: 'Compliance User', role: 'Employee', department: 'Compliance', password: 'COMPLIANCE@12345' },
  { id: 'delhi1', name: 'Delhi 1 User', role: 'Employee', department: 'Delhi 1', password: 'DELHI1@12345' },
  { id: 'delhi2', name: 'Delhi 2 User', role: 'Employee', department: 'Delhi 2', password: 'DELHI2@12345' },
  { id: 'dp', name: 'Dp User', role: 'Employee', department: 'Dp', password: 'DP@12345' },
  { id: 'kyc', name: 'Kyc User', role: 'Employee', department: 'Kyc', password: 'KYC@12345' },
  { id: 'customerservice', name: 'Customer Service User', role: 'Employee', department: 'Customer Service', password: 'CUSTOMER@12345' },
  { id: 'insurance', name: 'Insurance User', role: 'Employee', department: 'Insurance', password: 'INSURANCE@12345' },
];

export const seedRunners = ['Babulal', 'Atul', 'Narendra'];

export const seedRequests = [
  {
    id: 'TKT-8492',
    date: '2026-03-30T09:15:00.000Z',
    employeeName: 'Finance User',
    employeeId: 'finance',
    department: 'Finance',
    requestType: 'Pick-up',
    priority: 'High',
    pickupAddress: 'Tower A, 4th Floor, Finance Dept',
    dropAddress: 'Vendor Office, Sector 44',
    contactPerson: 'Mr. Sharma',
    mobileNumber: '9876543210',
    meetingTiming: '2026-03-31T14:00',
    description: 'Urgent tax documents for signature.',
    assignedPerson: 'Atul',
    lineupTiming: '2026-03-31T13:30',
    status: 'In Progress',
    adminComments: 'Runner dispatched.',
    completionDate: null,
  },
  {
    id: 'TKT-1023',
    date: '2026-03-29T11:00:00.000Z',
    employeeName: 'HR User',
    employeeId: 'hr',
    department: 'HR',
    requestType: 'Both',
    priority: 'Medium',
    pickupAddress: 'Candidate Home, DLF Phase 3',
    dropAddress: 'Tower B, Ground Floor HR',
    contactPerson: 'New Hire (Amit)',
    mobileNumber: '9988776655',
    meetingTiming: '2026-03-30T10:00',
    description: 'Onboarding laptop delivery and signed offer letter pickup.',
    assignedPerson: 'Babulal',
    lineupTiming: '2026-03-30T09:00',
    status: 'Completed',
    adminComments: 'Task finished successfully.',
    completionDate: '2026-03-30T11:30:00.000Z',
  },
];
